# This is a basic workflow to help you get started with Actions
- name: Psalm - Code quality tool for PHP
  # You may pin to the exact commit or the version.
  # uses: mickaelandrieu/psalm-ga@96d28f514148a75c861aa0e60e5007a858c71f78
  uses: mickaelandrieu/psalm-ga@v1.1

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
